-- Insert India-wide trips to database
INSERT INTO public.trips (trip_id, trip_name, duration, price_default, summary, highlights, inclusions, exclusions, images, locations, is_active, booking_live)
VALUES 
  ('manali-escape-009', 'Manali Snow & Mountains Adventure', '4D/3N', 14999, 
   'Explore the snow-capped Himalayas, visit Solang Valley, Rohtang Pass, and experience the charm of Old Manali.',
   ARRAY['Solang Valley adventure activities', 'Rohtang Pass snow experience', 'Old Manali cafes & culture', 'Hadimba Temple visit', 'Mall Road shopping & nightlife'],
   ARRAY['AC Volvo bus/Tempo Traveler', 'Hotel accommodation on triple sharing', '3 breakfasts, 3 dinners', 'Sightseeing as per itinerary', 'Entry fees to monuments', 'First aid support'],
   ARRAY['Adventure activities charges', 'Rohtang Pass permit (if applicable)', 'Personal expenses', 'Lunches', 'Tips and gratitude'],
   ARRAY['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80'],
   ARRAY['Manali', 'Solang Valley', 'Rohtang Pass', 'Old Manali', 'Vashisht'],
   true, false),
   
  ('goa-beach-bliss-010', 'Goa Beach Bliss — Sun, Sand & Vibes', '3D/2N', 11999,
   'Experience the best of Goa - pristine beaches, Portuguese heritage, vibrant nightlife, and delicious seafood.',
   ARRAY['North Goa beach hopping', 'Old Goa churches & heritage walk', 'Cruise on Mandovi River', 'Anjuna flea market', 'Beach shacks & nightlife'],
   ARRAY['AC transport', 'Resort stay on twin sharing', '2 breakfasts, 1 dinner', 'River cruise with snacks', 'Heritage walk guide', 'First aid support'],
   ARRAY['Water sports activities', 'Nightlife expenses', 'Alcoholic beverages', 'Personal shopping', 'Tips'],
   ARRAY['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80'],
   ARRAY['Goa', 'Calangute', 'Baga Beach', 'Old Goa', 'Panjim', 'Anjuna'],
   true, false),
   
  ('gokarna-beach-trek-011', 'Gokarna Beach Trek & Temple Town', '3D/2N', 8999,
   'Trek through pristine beaches, visit ancient temples, and experience the peaceful vibes of this hidden gem on Karnataka coast.',
   ARRAY['Beach trek - Om Beach to Paradise Beach', 'Mahabaleshwar Temple darshan', 'Sunset at Kudle Beach', 'Beach camping experience', 'Hidden beach exploration'],
   ARRAY['AC transport from Bangalore/Hubli', 'Hostel/Guesthouse stay', '2 breakfasts, 2 dinners', 'Trek guide', 'Boat ride', 'Bonfire setup', 'First aid support'],
   ARRAY['Water sports', 'Personal expenses', 'Lunches', 'Beverages'],
   ARRAY['https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80'],
   ARRAY['Gokarna', 'Om Beach', 'Kudle Beach', 'Paradise Beach', 'Half Moon Beach'],
   true, false),
   
  ('rishikesh-adventure-012', 'Rishikesh Adventure & Spirituality', '3D/2N', 9999,
   'River rafting, bungee jumping, ancient temples, and evening Ganga Aarti in the yoga capital of the world.',
   ARRAY['White water rafting on Ganges', 'Lakshman Jhula & Ram Jhula', 'Evening Ganga Aarti at Triveni Ghat', 'Cliff jumping & adventure activities', 'Beatles Ashram exploration'],
   ARRAY['AC transport from Delhi/Haridwar', 'Camp/hotel stay by river', '2 breakfasts, 2 dinners', 'White water rafting (16km)', 'Rafting equipment & guide', 'Bonfire', 'First aid support'],
   ARRAY['Bungee jumping, flying fox (optional paid)', 'Personal expenses', 'Lunches', 'Camera charges at attractions'],
   ARRAY['https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=800&q=80'],
   ARRAY['Rishikesh', 'Lakshman Jhula', 'Ram Jhula', 'Shivpuri', 'Neelkanth Temple'],
   true, false),
   
  ('udaipur-royal-013', 'Udaipur — City of Lakes & Palaces', '3D/2N', 12999,
   'Explore the Venice of the East - majestic palaces, serene lakes, vibrant bazaars, and royal Rajasthani heritage.',
   ARRAY['City Palace guided tour', 'Lake Pichola boat ride at sunset', 'Jag Mandir Island visit', 'Sajjangarh Monsoon Palace', 'Bagore Ki Haveli folk dance'],
   ARRAY['AC transport', 'Heritage hotel stay on twin sharing', '2 breakfasts, 1 dinner', 'City Palace entry', 'Boat ride on Lake Pichola', 'Bagore Ki Haveli entry', 'Sightseeing guide', 'First aid support'],
   ARRAY['Sajjangarh entry (nominal fee)', 'Personal shopping', 'Lunches', 'Tips'],
   ARRAY['https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=800&q=80'],
   ARRAY['Udaipur', 'City Palace', 'Lake Pichola', 'Jag Mandir', 'Sajjangarh'],
   true, false),
   
  ('jaipur-pink-city-014', 'Jaipur — The Pink City Royal Experience', '3D/2N', 10999,
   'Discover Rajasthan capital - magnificent forts, stunning palaces, vibrant markets, and rich Rajput heritage.',
   ARRAY['Amber Fort with elephant/jeep ride', 'Hawa Mahal & City Palace', 'Jantar Mantar astronomy tour', 'Nahargarh Fort sunset views', 'Johari Bazaar shopping'],
   ARRAY['AC transport', 'Heritage hotel stay on twin sharing', '2 breakfasts, 1 dinner (Chokhi Dhani)', 'Amber Fort jeep ride', 'Entry to all monuments', 'Sightseeing guide', 'First aid support'],
   ARRAY['Elephant ride (optional)', 'Personal shopping', 'Lunches', 'Tips', 'Camera fees'],
   ARRAY['https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80'],
   ARRAY['Jaipur', 'Amber Fort', 'Hawa Mahal', 'City Palace', 'Nahargarh Fort'],
   true, false)
ON CONFLICT (trip_id) DO UPDATE SET
  trip_name = EXCLUDED.trip_name,
  duration = EXCLUDED.duration,
  price_default = EXCLUDED.price_default,
  summary = EXCLUDED.summary,
  highlights = EXCLUDED.highlights,
  inclusions = EXCLUDED.inclusions,
  exclusions = EXCLUDED.exclusions,
  images = EXCLUDED.images,
  locations = EXCLUDED.locations,
  is_active = EXCLUDED.is_active;